FROM python:3.9-slim
WORKDIR /usr/src/app

# Copy the script to the container
COPY docker/scripts/execute.sh /usr/src/app/execute.sh

# Make the script executable
RUN chmod +x /usr/src/app/execute.sh

# Set the script as the entry point
ENTRYPOINT ["/usr/src/app/execute.sh"]
